### ISSUE TITLE
Table already exists.

### ISSUE THREAD

**Issue by eclyptox** [JoppeDC/SyliusBetterSeoPlugin#19]
Following installations steps, `doctrine:migrations:diff` throws this error:

```
In SchemaException.php line 108:                                                               
The table with name 'sylius.sylius_product' already exists.
```

**Comment by JoppeDC** [comment]
Hi @eclyptox ! 
Can you give me some more information? Are you already extending the products table in your project to add some custom functionality?
If so, you should use the trait that’s included.

**Comment by eclyptox** [comment]
No I have a project without extending Entities. Sylius 1.6.4 .

**Comment by JoppeDC** [comment]
> No I have a project without extending Entities. Sylius 1.6.4 .

Thanks for the response. Can you try step 4 of the readme before generating migrations? I think i might have that step mixed up there.

**Comment by eclyptox** [comment]
@JoppeDC same result. No luck.

**Comment by eclyptox** [comment]
@JoppeDC My base project is this https://github.com/Sylius/Sylius-Standard
Here is the Product entity extended.

**Comment by JoppeDC** [comment]
@eclyptox Okay, if the product is extended inside the project itself, you should use the SeoTrait that's included.
You can try it, and let me know how it goes.
I'll try myself tonight and add the scenario in more detail to the installation instructions.

Edit:
As long as you're not adding any custom functionality, you can change the resource models in `_sylius.yaml` to use my models. For examples of what to use, you can check [Resources.yaml](https://github.com/JoppeDC/SyliusBetterSeoPlugin/blob/master/src/Resources/config/resources.yaml)

**Comment by eclyptox** [comment]
Sorry for the delay. I have included your Trait, but your bundle sets your entities doctrine yaml config for your product entity, and it conflicts.
Is loading your mapping info:
![image](https://user-images.githubusercontent.com/710096/73200716-a6765100-4137-11ea-89a3-0b31b5b51fa2.png)
![image](https://user-images.githubusercontent.com/710096/73200763-be4dd500-4137-11ea-9419-7d4ef8f1f020.png)

**Comment by bybilvanis** [comment]
Same here, I think you can look at your version constraints. This plugin is not compatible with 1.6.4

**Comment by JoppeDC** [comment]
Thanks for the feedback y’all. I’m going to have to get deeper into the issue on the latest versions.
If i’m unable to get a quick fix ready, sadly i’ll have to add some constraints on incompatible versions.
If any of you find a solution by any chance, feel free to send in a PR with a possible fix.

**Comment by eclyptox** [comment]
@JoppeDC Finally I forked your project and removed doctrine mapping for product and taxon. Added to my entities and migration worked like a charm.

**Comment by bybilvanis** [comment]
> @JoppeDC Finally I forked your project and removed doctrine mapping for product and taxon. Added to my entities and migration worked like a charm.

Can you create a PR or share you patch pls?

**Comment by JoppeDC** [comment]
@eclyptox Thats great to hear! You can send a PR and i’ll check it out tomorrow 😉
Would also have to make sure it still works on older versions as well.

**Comment by JoppeDC** [comment]
This issue should be fixed in the latest release. If you're still running into this issue, make sure you're using v1.0.1 or up.

Thanks @antiseptikk

**Comment by eclyptox** [comment]
Sorry. I was out for a while. I will try to help more next time.

**Comment by shurco** [comment]
Sorry, but your fix doesn't work!

**Comment by JoppeDC** [comment]
@shurco quite a few things have changes since this issue. I recently installed this plugin in a fresh project and it worked with no issues.

Please make sure you’re using the latest version, and follow the instructions.
If the problem persists, please open a new issue with some more info and details

**Comment by shurco** [comment]
I am using the latest version of sylius and have followed the instructions.
But don't work (
