### ISSUE TITLE
I'll add Spanish translation

### ISSUE THREAD

**Issue by migmolrod** [JoppeDC/SyliusBetterSeoPlugin#3]
Let me know (ping me here in GitHub) if you add/remove/modify translation keys in the future, so I can update it.

**Comment by JoppeDC** [comment]
Well thanks! I haven’t even added all english translations yet it’s a very WIP project, but feel free to add!

**Comment by migmolrod** [comment]
Ok, I'll then watch the project to see the changes. If it happens I miss them, just ping me here in GitHub.
