### ISSUE TITLE
Update for sylius 1.11 and php 8.1

### ISSUE THREAD

**Issue by N445** [JoppeDC/SyliusBetterSeoPlugin#30]
An update is planned for sylius 1.11 and php 8.1 ?

Thanks

**Comment by N445** [comment]
Any news for this maj ?
This repo is always alive ?

**Comment by ngrdanjski** [comment]
composer require hellorse/sylius-better-seo-plugin

**Comment by JoppeDC** [comment]
Hi @N445  @ngrdanjski ,

I've been pretty occupied with other obligations.
Feel free to open a PR if you have the required changes, so i can check it out.

**Comment by JoppeDC** [comment]
Resolved in latest tag
